### ISSUE TITLE
Cannot be installed in latest macOS

### ISSUE THREAD

**Issue by zxch3n** [zxch3n/PomodoroLogger#110]
Need code signing maybe?

**Comment by haydlite** [comment]
Electron details [the process here](https://www.electronjs.org/docs/tutorial/code-signing). 

If you're not enrolled in Apple's Dev program, I think it'd be helpful to at least set up/enable checksum verification.

**Comment by zxch3n** [comment]
@haydlite Thanks. I know this signing process. But as you said, I'm not enrolled in the dev program. This is an offline application and it's open-source, the checksum may not be very helpful. I'll do it when I have more time to maintain this app

We actually can install Pomodoro Logger in macOS. It requires you to hold the `Command` button and right-click the app and click `Open`.
