### ISSUE TITLE
Screenshot feature not working on MacOS 10.14.6

### ISSUE THREAD

**Issue by mike-pomodoro** [zxch3n/PomodoroLogger#112]
**Describe the bug**

Screenshots do not appear to be recorded after enabling this feature.

**To Reproduce**

* Go to Setting -> Screenshot. Slider is selected (it's blue)
* Quit PomodoroLogger, then restart it for changes to take effect
* After starting a pomodoro and waiting for it to complete the ~/Library/Preferences/PomodoroLogger/screenshots/ directory is empty

**Expected behavior**

Should see screenshots.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version 10.14.6

**Comment by zxch3n** [comment]
Thanks for reporting the bug!
