### ISSUE TITLE
Pomodoro Heatmap is not updating Pomodoro heatmap (MacOS)

### ISSUE THREAD

**Issue by mike-pomodoro** [zxch3n/PomodoroLogger#116]
**Describe the bug**
Pomodoro Heatmap is not being updated after completing a pomodoro.

**To Reproduce**
1. Start a 25 minute pomodoro
2. Wait for it to complete
3. Start a 5 minute break
4. Wait for it to complete
5. Expect to see the Pomodoro Heatmap (under History tab) increment the pomodoro count for today
6. The pomodoro count is still zero (this was my first pomodoro today)
7. I upgraded to the latest PomodoroLogger 0.2.5 version yesterday; so this seems to be a regression (This functionality should still be working).

**Expected behavior**
The Pomodoro Heatmap should have updated the 2019-12-11 day with a pomodoro count of 1. Instead it shows 0(zero).

**Screenshots**

<img width="1025" alt="Screen Shot 2019-12-11 at 9 38 20 AM" src="https://user-images.githubusercontent.com/18354973/70645887-ac9d8600-1bfa-11ea-87d9-69d7b7e4b757.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14.6

**Additional context**

This problem is persistent (was having the same problem yesterday).

I may try reinstalling and deleting all the  PomodoroLogger files/directory under ~/Library.

**Comment by zxch3n** [comment]
Thanks for the detailed report. I will fix this soon.

The data should be recorded, it just does not present on the heatmap. If you reopen the app, you should see it.
