### ISSUE TITLE
"Quit Pomodoro-Logger" Hangs

### ISSUE THREAD

**Issue by mike-pomodoro** [zxch3n/PomodoroLogger#122]
**Describe the bug**

Pressing command-Q or clicking "Pomodoro Logger" -> "Quit pomodoro-logger" both result in the application hanging and not actually quitting.

After quitting these processes are left over (this is a "ps" output about 20 minutes after pressing Command-Q to quit):

> $ ps -ef | grep  [P]omodoro
>   503 52411     1   0 12:13AM ??         6:45.24 /Applications/Pomodoro Logger.app/Contents/MacOS/Pomodoro Logger
>   503 52412 52411   0 12:13AM ??        16:04.13 /Applications/Pomodoro Logger.app/Contents/Frameworks/Pomodoro Logger Helper (GPU).app/Contents/MacOS/Pomodoro Logger Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,2334290031395571857,2845403641233504882,131072 --disable-features=SpareRendererForSitePerProcess --gpu-preferences=IAAAAAAAAAAgAAAAAAAAAAAAYAAAAAAACAAAAAAAAAAIAQAAIAAAAAABAAAAAAAACAEAAAAAAAAQAQAAAAAAABgBAAAAAAAAIAEAAAAAAAAoAQAAAAAAADABAAAAAAAAOAEAAAAAAABAAQAAAAAAAEgBAAAAAAAAUAEAAAAAAABYAQAAAAAAAGABAAAAAAAAaAEAAAAAAABwAQAAAAAAAHgBAAAAAAAAgAEAAAAAAACIAQAAAAAAAJABAAAAAAAAmAEAAAAAAACgAQAAAAAAAKgBAAAAAAAAsAEAAAAAAAC4AQAAAAAAAMABAAAAAAAAyAEAAAAAAADQAQAAAAAAANgBAAAAAAAA4AEAAAAAAADoAQAAAAAAAPABAAAAAAAA+AEAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAAAAAAcAAAAQAAAAAAAAAAAAAAAIAAAAEAAAAAAAAAAAAAAACgAAABAAAAAAAAAAAAAAAAsAAAAQAAAAAAAAAAAAAAANAAAAEAAAAAAAAAAAAAAADgAAABAAAAAAAAAAAQAAAAAAAAAQAAAAAAAAAAEAAAAGAAAAEAAAAAAAAAABAAAABwAAABAAAAAAAAAAAQAAAAgAAAAQAAAAAAAAAAEAAAAKAAAAEAAAAAAAAAABAAAACwAAABAAAAAAAAAAAQAAAA0AAAAQAAAAAAAAAAEAAAAOAAAAEAAAAAAAAAAEAAAAAAAAABAAAAAAAAAABAAAAAYAAAAQAAAAAAAAAAQAAAAHAAAAEAAAAAAAAAAEAAAACAAAABAAAAAAAAAABAAAAAoAAAAQAAAAAAAAAAQAAAALAAAAEAAAAAAAAAAEAAAADQAAABAAAAAAAAAABAAAAA4AAAAQAAAAAAAAAAYAAAAAAAAAEAAAAAAAAAAGAAAABgAAABAAAAAAAAAABgAAAAcAAAAQAAAAAAAAAAYAAAAIAAAAEAAAAAAAAAAGAAAACgAAABAAAAAAAAAABgAAAAsAAAAQAAAAAAAAAAYAAAANAAAAEAAAAAAAAAAGAAAADgAAAA== --service-request-channel-token=2392428924634228588
>   503 52414 52411   0 12:13AM ??        34:10.01 /Applications/Pomodoro Logger.app/Contents/Frameworks/Pomodoro Logger Helper (Renderer).app/Contents/MacOS/Pomodoro Logger Helper (Renderer) --type=renderer --disable-background-timer-throttling --field-trial-handle=1718379636,2334290031395571857,2845403641233504882,131072 --disable-features=SpareRendererForSitePerProcess --lang=en-US --app-path=/Applications/Pomodoro Logger.app/Contents/Resources/app.asar --node-integration --node-integration-in-worker --no-sandbox --no-zygote --background-color=#fff --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --service-request-channel-token=17655023121276010960 --renderer-client-id=4 --no-v8-untrusted-code-mitigations

Some dtruss output on the Pomodoro Logger processes.

> 
> $  sudo dtruss -p 52411
> Password:
> dtrace: system integrity protection is on, some features will not be available
> 
> SYSCALL(args) 		 = return
> workq_kernreturn(0x40, 0x700007C60B80, 0x0)		 = 0 Err#-2
> kevent_qos(0xFFFFFFFFFFFFFFFF, 0x7FFEE0B7B1B0, 0x1)		 = 0 0
> sysctlbyname(kern.memorystatus_vm_pressure_level, 0x23, 0x7FFEE0B7C92C, 0x7FFEE0B7C920, 0x0)		 = 0 0
> workq_kernreturn(0x40, 0x700007C60B80, 0x1)		 = 0 Err#-2
> workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
> thread_selfid(0x0, 0x0, 0x0)		 = 2275502 0
> 

> $ sudo dtruss -p 52412
> dtrace: system integrity protection is on, some features will not be available
> SYSCALL(args) 		 = return
> __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
> 

> $ sudo dtruss -p 52414
> dtrace: system integrity protection is on, some features will not be available
> SYSCALL(args) 		 = return
> kevent_qos(0xFFFFFFFFFFFFFFFF, 0x7FFEE50BE0E0, 0x1)		 = 0 0
> workq_kernreturn(0x40, 0x70000F345B80, 0x1)		 = 0 Err#-2
> kevent_qos(0xFFFFFFFFFFFFFFFF, 0x7FFEE50BDFA0, 0x1)		 = 0 0
> workq_kernreturn(0x40, 0x70000F345B80, 0x0)		 = 0 Err#-2
> workq_kernreturn(0x40, 0x70000F345B80, 0x1)		 = 0 Err#-2
> kevent_qos(0xFFFFFFFFFFFFFFFF, 0x7FFEE50BE0E0, 0x1)		 = 0 0
> workq_kernreturn(0x40, 0x70000F345B80, 0x1)		 = 0 Err#-2
> kevent_qos(0xFFFFFFFFFFFFFFFF, 0x7FFEE50BDFA0, 0x1)		 = 0 0
> workq_kernreturn(0x40, 0x70000F345B80, 0x0)		 = 0 Err#-2
> workq_kernreturn(0x40, 0x70000F345B80, 0x1)		 = 0 Err#-2
> kevent_qos(0xFFFFFFFFFFFFFFFF, 0x7FFEE50BE0E0, 0x1)		 = 0 0
> 

**Desktop (please complete the following information):**
 - OS: MacOS/MacBook Pro 15" 2017
 - Version 10.14.6

**Additional context**

This problem happens 100% of the time.

I'm not able to cleanly quit.

I exit by running "pkill -HUP -f Pomodoro".

I have to run pkill twice for some reason before all the processes exit.

I upgraded to the  latest Pomodoro Logger yesterday and still see the quit bug.

**Comment by zxch3n** [comment]
Can you exit the app by right-clicking the icon in the tray and click "Quit"?

I might be slow to fix this issue because I don't have access to a macOS recently and it doesn't happen on Win10.

**Comment by mike-pomodoro** [comment]
Nope.

If I right-click Quit in the tray to quit, it still hangs.

**Comment by mike-pomodoro** [comment]
Another data point.

I followed the steps on the contribution page:
https://github.com/zxch3n/PomodoroLogger/blob/master/.github/CONTRIBUTION.md
and ran "yarn start-dev".

The Electron app starts properly and I can use it just fine, but when I click "Electron -> Quit pomodoro-logger" or press Command-Q it also hangs and does not exit.

**Comment by mike-pomodoro** [comment]
Interesting.

I downloaded the latest release 0.2.7 and if I click the Pomodoro Logger icon on the right-side of the menu bar (the bar at the top of my screen) and click "Quit", it quits properly.

If I quit using command-Q or click "Pomodoro Logger" on the left-side of the menu bar and then "Quit"  it hangs in 0.2.7.

Not sure if this is the same behavior in versions prior to 0.2.7 (since I didn't try to quit using the Pomodoro Logger Icon->Quit sequence in previous versions.)

**Comment by zxch3n** [comment]
Thanks for your work! Your information is very helpful.
