### ISSUE TITLE
Lists are not updated immediately after adding a new one

### ISSUE THREAD

**Issue by cyan-gorilla** [zxch3n/PomodoroLogger#126]
**Describe the bug**
After adding a new list to a board, it is not shown immediately.

**To Reproduce**
1. Go to 'Kanban'
2. Click on any board
3. Click on the plus button to add a new list

**Expected behavior**
The list appears in the board right after pressing the '+' button.

**Actual behavior**
The list doesn't appear right away. You have to go back to the boards and enter the one you were modifying to see it.

**Screenshots**
![QkoFMd10pc](https://user-images.githubusercontent.com/56950011/71476703-24f07380-27c5-11ea-89e6-da890d4cdc6a.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.2.8.0

**Additional context**
This resulted in adding many unnecessary lists, which added to #125 means a miserable time deleting them

**Comment by zxch3n** [comment]
Thanks for reporting this!
