### ISSUE TITLE
A javascript error occured in main process

### ISSUE THREAD

**Issue by cdne** [zxch3n/PomodoroLogger#129]
**Describe the bug**
When I open the app after I close it with right click "Quit" in taskbar this error appears (see screenshot 1). Also it seems if I click Distracting App Settings when I create a new board, app goes blank (see screenshot 2).

**To Reproduce**
1. Close app with "Quit" in task bar
2. Open app again

**Screenshots**

Screenshot 1
![image](https://user-images.githubusercontent.com/55295404/75058429-a887c180-54e3-11ea-90f8-a2d201f71a55.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/55295404/75058816-6448f100-54e4-11ea-9120-798b87ef7a25.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version:

![image](https://user-images.githubusercontent.com/55295404/75058528-d7059c80-54e3-11ea-9ab1-dc5c0bc8dc2c.png)

**Additional context**
This error appeared first when I installed the app first time on windows.

**Comment by zxch3n** [comment]
Fixed in v0.2.11
