### ISSUE TITLE
很棒的番茄钟，能否优化下系统资源占用？

### ISSUE THREAD

**Issue by zhaoliang0302** [zxch3n/PomodoroLogger#131]
运行占用内存约为200M。
![image](https://user-images.githubusercontent.com/42333702/75686343-151a7180-5cd7-11ea-93d4-c14dc429798d.png)
感谢你的开发

**Comment by zxch3n** [comment]
好的，我会尝试优化一下

**Comment by zxch3n** [comment]
在几个 commit 中去掉了多余的内存使用，现内存占 100MB。因为使用的是 electron，剩余的优化空间不是很大，先 Close 该 issue。

如果还有影响使用的情况欢迎重开该 issue 😸
