### ISSUE TITLE
FEATURE REQUEST: Ability to collapse/expand kanban card Content

### ISSUE THREAD

**Issue by jrykowski-huron** [zxch3n/PomodoroLogger#133]
Use Case: Capturing To Do items for the task sometimes involves many steps or detail and the size of card displayed takes up entire visible kanban column.

Need to be able to collapse the Content details and expand (if collapsed).   Standard ^ v icons or +/-?

Ability to expand or collapse all cards would nice to have.

**Comment by zxch3n** [comment]
Yeah! You are right

**Comment by zxch3n** [comment]
Done in  https://github.com/zxch3n/PomodoroLogger/commit/201c2757b76d124b9f267c8767438b94752f2913
