### ISSUE TITLE
Choosing different kanban board on timer page does not switch In Progress card

### ISSUE THREAD

**Issue by jrykowski-huron** [zxch3n/PomodoroLogger#134]
**Describe the bug**

When choosing different kanban board from select list under Pomodoro timer, the kanban board changes but current In Progress card does not.

WORK AROUND: Choose "No focus project" then choose the kanban board you want to switch to - the in progress card is correctly shown.

**Expected behavior**
When choosing different Kanban board to work on, the current in progress card should change to be the one for the kanban board selected.

**Desktop (please complete the following information):**
 - OS: win10
 - Version 0.2.10.0

**Comment by zxch3n** [comment]
Will fix soon

**Comment by jrykowski-huron** [comment]
Nice work!  Thank you.

**Comment by jrykowski-huron** [comment]
I tested latest release and this issue was resolved.
