### ISSUE TITLE
How to add app distraction on MacOS.

### ISSUE THREAD

**Issue by romariorobby** [zxch3n/PomodoroLogger#135]
What should be filled on RegEx on macOS? Could you give me example for MacOS? Thanks

**Comment by zxch3n** [comment]
You can see the app name on the first column of the Sankey Diagram.

![image](https://user-images.githubusercontent.com/18425020/78320315-c133ce80-759b-11ea-8a85-12534f379e88.png)

For example, if you want to make Chrome as a distracting app, you can add a field in distracting app setting. And fill `Google Chrome` in `App` field, as below

![image](https://user-images.githubusercontent.com/18425020/78320485-2e476400-759c-11ea-9fbd-65886ebbf1bb.png)

Then all your activities in Chrome will be seen as distracted:

![image](https://user-images.githubusercontent.com/18425020/78320592-6353b680-759c-11ea-83b3-dbc896c06c78.png)
