### ISSUE TITLE
In Progress里两个任务耗时增加

### ISSUE THREAD

**Issue by Aledenn** [zxch3n/PomodoroLogger#146]
**Describe the bug**
请问每次完成一个番茄 In Progress里两个耗时都会同时增加 本来就是这么设计的吗？
![image](https://user-images.githubusercontent.com/19233912/81669766-3f2ba500-9479-11ea-849b-7360dcda5bf9.png)

**Comment by zxch3n** [comment]
确实是这样设计的，但很不直观也造成了很多误会，未来会修改这个行为。 #145  提出了一种方案，还不是很完善，欢迎评论
