### ISSUE TITLE
When search filtered, wrong kanban card gets moved to other list when dragging from Column A to Column B

### ISSUE THREAD

**Issue by jrykowski-huron** [zxch3n/PomodoroLogger#147]
Wrong Kanban card gets moved when board is filtered.

1. On Kanban, create a Column A and Column B set of cards,
2. Add more than 3 cards to Column A set of cards
3. Use the Search filter to limit Column A to finding only 1 item (preferably the last item because issue will be more apparent),
4. Click and drag that single item from Column A to Column B (be aware of its title - it should be the one that was last in list before filtered),
   ** symptom: you'll see the card blink back to Column A after you've dropped it on Column B,
5. Unfillter the kanban board (remove the search filter),
6. You'll see whatever card was at top (index 0) of Column A list now shows in Column B

Wrong card gets moved when dragging from Column A to Column B when list is filtered.

**Expected behavior**
The selected card from Column A (the one that is clicked not simply the one that is at position 0) needs to be the one moved to Column B when dragged.   Bug seems to be that logic is assuming the lists aren't filtered, so when clicking item (when its only one in the list) it assumes that is Column A item at top of list - but it could be at any position in the list since filtered.

**Desktop (please complete the following information):**
 - OS: win10
 - Version v0.3.2

**Comment by jrykowski-huron** [comment]
Very much appreciate the kanban functionality of PomodoroLogger - it was the reason gravitated to this tool when looking for pomodoro timer.   I use the kanban board to manage an otherwise chaotic set of shifting priorities throughout the day (I work as DevOps engineer and task switch between automation development work and operations/support).

**Comment by zxch3n** [comment]
Thanks for the detailed bug report! A number of different projects, which is hard to prioritize and review, is also the very reason that I make this tool.

**Comment by zxch3n** [comment]
Fixed in v0.3.3
