### ISSUE TITLE
增加mini视图/模式

### ISSUE THREAD

**Issue by ym-xk** [zxch3n/PomodoroLogger#148]
类似某些音乐播放器的mini模式
小窗口&置顶显示
可以更直观的看到番茄钟倒计时并进行暂停/重置/完成
╔═══════════════════════════╗
║  Working    [ 23:59 ]         ▷pause | ↻reset | √finish  ║
╚═══════════════════════════╝

（另外是否可以在任务栏显示为进度条式

**Comment by zxch3n** [comment]
谢谢！👌，进度条的需要尝试一下
