### ISSUE TITLE
Arch Linux User

### ISSUE THREAD

**Issue by pemudakoding** [zxch3n/PomodoroLogger#150]
Hello dude !, this package can installed on arch linux ? if it's can how installing it ?
thank you

**Comment by zxch3n** [comment]
You can download the installer in [release page](https://github.com/zxch3n/PomodoroLogger/releases/latest). The file ends with `.deb` is for the Linux system.

**Comment by mizhozan** [comment]
> Hello dude !, this package can installed on arch linux ? if it's can how installing it ? thank you

You may also check #214 for an AUR package.
