### ISSUE TITLE
[enhancement] Prompt for Save if card contents modified but Save not clicked to close

### ISSUE THREAD

**Issue by slightlybent** [zxch3n/PomodoroLogger#156]
It would be really good to prompt "Save changes?" if contents changed and accidentally clicking off of the card being Edited.

I've lost my changes more times than I care to admit when forgetting to click Save before clicking outside of the card (which closes it as if Cancel was selected).  Doh!

**Comment by zxch3n** [comment]
I removed the cancel behavior, as it is not useful. In the latest version, everything will be saved after editing.
