### ISSUE TITLE
Import data feature

### ISSUE THREAD

**Issue by faruzzy** [zxch3n/PomodoroLogger#159]
**Describe the bug**
Sorry if this is not how I should have proceeded but the Readme indicates that I can import / export /delete all my data.
I've got a new machine that I'm trying to setup with my all data which I was able to export from old computer.
After getting a new install of Pomodoro Logger, I don't see a way of importing the data.

**To Reproduce**
1. Go to 'Setting'
2. There's no Import options only a `delete all data` option

**Expected behavior**
There should be a button for importing data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Version 10.14.6

**Comment by MuhammedZakir** [comment]
> I've got a new machine that I'm trying to setup with my all data which I was able to export from old computer.

Were you using an old version when exporting? Because I could not find an export option in settings.

**Comment by furtivesock** [comment]
Hello,
I don't have import feature too but you can instead copy and paste all `.nedb` file from `...\PomodoroLogger\db` to your new `db` directory.

**Comment by faruzzy** [comment]
> > I've got a new machine that I'm trying to setup with my all data which I was able to export from old computer.
> 
> Were you using an old version when exporting? Because I could not find an export option in settings.

Yes I had an old version that allowed me to export

**Comment by zxch3n** [comment]
Sorry for the late reply.

v0.4.0 now supports exporting and importing data again!

- The old version of data importing would overwrite all the local data.
- In v0.4.0, importing will solve the conflict and merge local data with imported data
