### ISSUE TITLE
Cannot run the app from the source

### ISSUE THREAD

**Issue by bartosz-jarmuz** [zxch3n/PomodoroLogger#165]
Hello,

I'd like to contribute to the app, but so far I cannot run it by compiling sources (I have no experience with Electron apps!). 

I am running Windows 10, and the executable release works fine.

I have installed node.js, node-gyp, yarn, electron, commonjs, webpack etc.

I execute yarn, yarn build and yarn test commands from main directory of cloned repo and both commands run fine.

Then I run yarn start-main-dev and... not much happens:
Not sure what 'should' happen, but that's it.
![image](https://user-images.githubusercontent.com/33833009/94698399-90a9d300-0339-11eb-802f-0ce2157a5e96.png)

I then try the 'yarn start' command which again throws no errors
![image](https://user-images.githubusercontent.com/33833009/94698769-ee3e1f80-0339-11eb-8f4c-a17e540540f5.png)

I then try accessing the local host in chrome and the app logo shows up, but dev tools show the following error and nothing else happens:

![image](https://user-images.githubusercontent.com/33833009/94699093-3f4e1380-033a-11eb-8ee3-321664b11dd1.png)

I also tried going to /dist folder and running electron main.js, but then the following error happens:

![image](https://user-images.githubusercontent.com/33833009/94699310-791f1a00-033a-11eb-9d47-25df5db71b1a.png)

Please let me know how should it work.
Kind regards,
Bartek

**Comment by zxch3n** [comment]
I recently changed the dev method. After `yarn start` you need to run `npx electron .` 

(I should've updated the contribution guide)

**Comment by bartosz-jarmuz** [comment]
Hello,
Thanks for answer, but... I still get an error
![image](https://user-images.githubusercontent.com/33833009/94813363-29068d00-03f8-11eb-818c-9372b28cad44.png)

**Comment by zxch3n** [comment]
You should run `yarn start` first, then in another terminal issue `npx electron .`

**Comment by bartosz-jarmuz** [comment]
Ok, that worked, although there's still an error in console... and the dev tools keep shooting out lots of errors constantly:

![image](https://user-images.githubusercontent.com/33833009/94901364-d4661f00-0496-11eb-97a2-c5745b28aa01.png)

**Comment by zxch3n** [comment]
Have you tried run `npx electron  .`  after `yarn start` finish its first building (when you see no error found)? Because it depends on the built production of the main process which is built after `yarn start`

**Comment by bartosz-jarmuz** [comment]
Yes, that's what I did.
- yarn
- yarn start
- wait
- open new bash
- npx electron .

It works "better" because the apps seems usable, but dev tools show a continuous flow of errors , and there is one error in bash.

**Comment by zxch3n** [comment]
That's odd. It works fine on my devices. Maybe because some deps install failed. Could you try remove yarn.lock and node_modules and `yarn` again? If there are error messages during `yarn` please let me know.

**Comment by bartosz-jarmuz** [comment]
Removing the yarn lock helped (although there were still some errors, but it seems the app is running fine).

When I downloaded the newest version of your repo, it also worked.

Thanks a lot for support  and for maintaining this nice project. I hope I'll be able to contribute a bit.
