### ISSUE TITLE
Single quotation marks are rendered weirdly on descriptions

### ISSUE THREAD

**Issue by furtivesock** [zxch3n/PomodoroLogger#170]
Hello!
Firstly I want to thank you a lot for this helpful app. 😄 

**Describe the bug**
When you add a single quotation mark `'` in the text of a kanban board or card description, this displays a weird tag: `&#39;`. It's not convenient for contractions (for instance).

**To Reproduce**
1. Edit a card or the description of a kanban board.
2. Add a single quotation mark `'`.
3. Go to **Preview** or save the description.

**Expected behavior**
It is supposed to show a single quotation mark as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/38814441/96411349-92541180-11e8-11eb-986c-42afe4ed4e87.png)
![image](https://user-images.githubusercontent.com/38814441/96411297-8405f580-11e8-11eb-83cd-9b13391dde5b.png)

**Desktop (please complete the following information):**
 - OS: win10 (tried on two different computers)

**Comment by zxch3n** [comment]
Thanks! It's fixed in v0.5.2
