### ISSUE TITLE
Configurable threshold of applications to be viewed

### ISSUE THREAD

**Issue by bartosz-jarmuz** [zxch3n/PomodoroLogger#172]
**Is your feature request related to a problem? Please describe.**
The statistics chart is not very clear, because it contains too many insignificant entries.

**Describe the solution you'd like**
Allow only showing applications which were used above a certain percentage level. E.g. Only apps used above 5% of time?

![image](https://user-images.githubusercontent.com/33833009/96991836-5642e880-1529-11eb-93f6-0da34086f806.png)

**Comment by zxch3n** [comment]
In the current version, only top 10 apps display in the chart. In the [commit](https://github.com/zxch3n/PomodoroLogger/commit/dcb9ba928d66ebffadad734e56b95abc8ddc10c5), apps used less than 5% of the time are ignored.

**Comment by bartosz-jarmuz** [comment]
Thanks for looking into it!
