### ISSUE TITLE
Display statistics with time, not just number of pomodoros

### ISSUE THREAD

**Issue by bartosz-jarmuz** [zxch3n/PomodoroLogger#174]
**Is your feature request related to a problem? Please describe.**
When I see a number of pomodors done today/this week, I don't know what is the amount of hours.

**Describe the solution you'd like**
I'd like to see the number of hours spent, next to the number of pomodoros, everywhere where its displayed (or instead, depending of the user setting)

![image](https://user-images.githubusercontent.com/33833009/96992389-1fb99d80-152a-11eb-8da7-48f35590c34c.png)

**Describe alternatives you've considered**
Either display both values or allow setting this in settings to display number of pomodoros or the amount of hours.

**Comment by zxch3n** [comment]
Resolved in v0.5.3

**Comment by bartosz-jarmuz** [comment]
Thanks!!
