### ISSUE TITLE
Status Report Request

### ISSUE THREAD

**Issue by gotjoshua** [zxch3n/PomodoroLogger#232]
Greetings,
I found and [forked](https://github.com/onezoomin/PomodoroLogger/issues) your project today, and I am quite impressed with the code organization and core functionality! Thanks for sharing this with the FOSS community at large!

I made a [list of the first issues that I intend to address in my fork](https://github.com/onezoomin/PomodoroLogger/issues).

I am writing here to invite feedback and to request an official status update from @zxch3n  as the maintainer...
Do you have any intentions of picking up the project any time soon?

**Comment by zxch3n** [comment]
Cool! I'm happy to see that you want to refactor the persistence layer.

I can't spend too much time on this project lately. But I'd love to review your PRs. 

Did you consider using something like pouchDB as the new db? It works on both browser and node.
