### ISSUE TITLE
Warning: You are using a version of node-ipc containing malicious code

### ISSUE THREAD

**Issue by lukas-mertens** [zxch3n/PomodoroLogger#239]
I just wanted to warn you about a current version of node-ipc containing https://github.com/RIAEvangelist/peacenotwar. You should probably pin your dependencies.

You can read more about it here: https://github.com/RIAEvangelist/node-ipc/issues/233

**Comment by zxch3n** [comment]
OMG, I’m looking into it. Thank you!

**Comment by zxch3n** [comment]
Fixed. Thanks for the reminding

**Comment by lukas-mertens** [comment]
No problem. I hope your files were not deleted.
