### ISSUE TITLE
Export and import data feature does not work

### ISSUE THREAD

**Issue by Finishxx** [zxch3n/PomodoroLogger#241]
After installing the latest update 0.6.2 I can't export or import data anymore. I tried reinstalling too, but that doesn't solve the problem and installation of older versions freezes in the process. Except for version 0.6.1, which does not work in the same way as 0.6.2. I am running windows 10 build 19044.1586. 

EDIT: In the end I found a fix: I managed to install version 0.4.0, where the export works.

Thank you for this amazing app, it has helped me tons!

**Comment by zxch3n** [comment]
Thanks. Should be fixed on v0.6.3
