### ISSUE TITLE
UI Responsiveness: The first two month names are overlapping

### ISSUE THREAD

**Issue by durgakiran** [zxch3n/PomodoroLogger#84]
- OS: windows 10 X64.
I observed that first two month names are overlapping(not checked in latest master build). Screen shot attached.
![pomodoro logger overlap](https://user-images.githubusercontent.com/17452039/65476714-737a3300-dea1-11e9-8bf2-fb739a4535cc.png)

**Comment by durgakiran** [comment]
some contributing guidelines would be helpful for people who look to be part of open source software :)

**Comment by zxch3n** [comment]
Agree. Thanks for your feedback!
